-- 코드를 입력하세요
-- 판매중인 도서 정보 BOOK
-- 저자 정보 AUTHOR
-- BOOK_SALES
-- 2022년 1월, 저자 별, 카테고리 별 매출액

# SELECT C.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, A.SALES * B.PRICE AS TOTAL_SALES
# FROM BOOK_SALES A
# LEFT JOIN BOOK B
# JOIN AUTHOR C
# ON A.BOOK_ID = B.BOOK_ID AND
# B.AUTHOR_ID = C.AUTHOR_ID
# WHERE DATE_FORMAT(A.SALES_DATE, '%Y-%m') = '2022-01'
# ORDER BY C.AUTHOR_ID, B.CATEGORY DESC

# SELECT B.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, SUM(A.SALES) * B.PRICE AS TOTAL_SALES
# FROM BOOK_SALES A
# JOIN BOOK B
# LEFT JOIN AUTHOR C
# ON A.BOOK_ID = B.BOOK_ID
# AND B.AUTHOR_ID = C.AUTHOR_ID
# WHERE DATE_FORMAT(A.SALES_DATE, '%Y-%m') = '2022-01'
# # AND C.AUTHOR_ID IS NOT NULL
# GROUP BY A.BOOK_ID, B.AUTHOR_ID, B.CATEGORY
# ORDER BY C.AUTHOR_ID, B.CATEGORY DESC;

# WITH A AS (SELECT BOOK_ID, SUM(SALES) AS SALES
# FROM BOOK_SALES
# WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
# GROUP BY BOOK_ID)


# SELECT B.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, (A.SALES * B.PRICE) AS TOTAL_SALES
# FROM A LEFT JOIN BOOK B
# JOIN AUTHOR C
# ON A.BOOK_ID = B.BOOK_ID
# AND B.AUTHOR_ID = C.AUTHOR_ID
# GROUP BY A.BOOK_ID, B.AUTHOR_ID, B.CATEGORY
# ORDER BY B.AUTHOR_ID, B.CATEGORY DESC;


SELECT 
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES S
JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE DATE_FORMAT(S.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC;