-- 코드를 입력하세요


# SELECT DISTINCT A.CAR_ID, A.CAR_TYPE,
#     ROUND((1 - C.DISCOUNT_RATE / 100) * A.DAILY_FEE * 30, 0) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR A
# LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE
# WHERE A.CAR_TYPE IN ('세단', 'SUV')
#     AND (B.START_DATE > '2022-11-30' OR B.END_DATE < '2022-11-01')
#     AND DURATION_TYPE = '30일 이상'
#     AND (((1 - C.DISCOUNT_RATE / 100) * A.DAILY_FEE * 30) >= 500000 AND
#         ((1 - C.DISCOUNT_RATE / 100) * A.DAILY_FEE * 30) < 2000000)
# ORDER BY ROUND((1 - C.DISCOUNT_RATE / 100) * A.DAILY_FEE, 0) * 30 DESC, CAR_TYPE, CAR_ID DESC


SELECT DISTINCT A.CAR_ID, A.CAR_TYPE,
    ROUND((1 - C.DISCOUNT_RATE / 100) * A.DAILY_FEE * 30, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C 
    ON A.CAR_TYPE = C.CAR_TYPE AND C.DURATION_TYPE = '30일 이상'
WHERE A.CAR_TYPE IN ('세단', 'SUV')
  AND NOT EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE H.CAR_ID = A.CAR_ID
      AND H.START_DATE <= '2022-11-30'
      AND H.END_DATE >= '2022-11-01'
)
  AND ROUND((1 - C.DISCOUNT_RATE / 100) * A.DAILY_FEE * 30, 0) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC;

