-- 코드를 입력하세요

-- 중고 거래 게시물을 3건 이상 등록한 사용자
WITH UGB AS (
    SELECT WRITER_ID, COUNT(*) AS CNT
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
)

SELECT
    USER_ID,
    NICKNAME,
    CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) AS 전체주소,
    CONCAT(LEFT(TLNO, 3), "-", SUBSTR(TLNO, 4, 4), "-", RIGHT(TLNO, 4)) AS 전화번호
FROM UGB A
JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
WHERE A.CNT >= 3
ORDER BY USER_ID DESC
