-- 코드를 작성해주세요

SELECT COUNT(B.FISH_TYPE) AS FISH_COUNT, FISH_NAME
FROM FISH_NAME_INFO A
JOIN FISH_INFO B ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY B.FISH_TYPE, FISH_NAME
ORDER BY COUNT(B.FISH_TYPE) DESC;
