-- 2021년에 가입한 전체 회원들 중
-- 상품을 구매한 회원수와 상품을 구매한 회원의 비율
-- 구매한 회원수 / 가입한 전체 회원수


-- 2021년 가입한 회원
WITH USER_CNT AS (
    SELECT COUNT(*) AS CNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'

)


SELECT 
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    ROUND((COUNT(DISTINCT USER_ID) / USER_CNT.CNT), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE, USER_CNT
WHERE USER_ID IN (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)


-- 21년에 가입한 회원들 중, 상품을 구매한 회원수, 상품을 구매한 회원의 비율