-- 코드를 입력하세요
-- PRODUCT_ID
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(B.AMOUNT) * A.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT A
JOIN FOOD_ORDER B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE YEAR(B.PRODUCE_DATE) = '2022' AND MONTH(B.PRODUCE_DATE) = '05'
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID

# SELECT * FROM FOOD_PRODUCT;

# SELECT * FROM FOOD_ORDER;
