WITH RENT AS (
    SELECT
        HISTORY_ID,
        A.CAR_ID,
        B.CAR_TYPE,
        B.DAILY_FEE,
        DATEDIFF(END_DATE, START_DATE) + 1 AS DAYS,
    CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
    ELSE '7일 미만' END AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
    JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
    WHERE B.CAR_TYPE = '트럭'

)

SELECT
    A.HISTORY_ID,
    FLOOR(((100 -  IFNULL(B.DISCOUNT_RATE, 0)) / 100) * A.DAILY_FEE * A.DAYS) AS FEE
FROM RENT A
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B 
ON A.CAR_TYPE = B.CAR_TYPE AND A.DURATION = B.DURATION_TYPE
ORDER BY FEE DESC, A.HISTORY_ID DESC
