-- 코드를 입력하세요

-- 7월에는 아이스크림 출고량이 많아 두 개의 공장에서 생산하므로, 맛에 대하여 다른 출하 id를 가질 수 있음.

WITH B AS  (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)

SELECT A.FLAVOR
FROM FIRST_HALF A
JOIN B ON A.FLAVOR = B.FLAVOR
GROUP BY A.FLAVOR
ORDER BY A.TOTAL_ORDER + B.TOTAL_ORDER DESC
LIMIT 3

# SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
#     FROM JULY
#     GROUP BY FLAVOR;

