-- 코드를 입력하세요
-- ANIMAL_OUTS

WITH RECURSIVE HH AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1 FROM HH
    WHERE HOUR < 23
)


SELECT A.HOUR AS HOUR, COUNT(B.ANIMAL_ID) AS COUNT
FROM HH A
LEFT JOIN ANIMAL_OUTS B ON A.HOUR = HOUR(B.DATETIME)
GROUP BY A.HOUR
ORDER BY A.HOUR