-- 코드를 입력하세요
-- USED_GOODS_BOARD: 중고 거래 게시판 정보
-- USED_GOODS_USER : 중고 거래 게시판 사용자 정보
-- 완료된 중고 거래의 총금액 >= 70만
# SELECT USER_ID, NICKNAME, TOTAL_SALES
# FROM USED_GOODS_BOARD A
# JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID

WITH B AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000
    )

SELECT A.USER_ID, A.NICKNAME, B.TOTAL_SALES
FROM USED_GOODS_USER A
JOIN B ON A.USER_ID = B.WRITER_ID
ORDER BY B.TOTAL_SALES