-- 코드를 작성해주세요



-- HR_DEPARTMENT.DEPT_ID = HR_EMPLOYEES.DEPT_ID
-- HR_EMPLOYEES .EMP_NO = HR_GRADE.EMP_NO

-- 사원별 성과금 정보를 조회

WITH HR_BONUS AS (
    SELECT EMP_NO, SUM(SCORE) / 2,
        CASE WHEN SUM(SCORE) / 2 >= 96 THEN 0.2
        WHEN SUM(SCORE) / 2 >= 90 THEN 0.15
        WHEN SUM(SCORE) / 2 >= 80 THEN 0.1
        ELSE 0 END AS PERCENT,
        CASE WHEN SUM(SCORE) / 2 >= 96 THEN 'S'
        WHEN SUM(SCORE) / 2 >= 90 THEN 'A'
        WHEN SUM(SCORE) / 2 >= 80 THEN 'B'
        ELSE 'C' END AS EVAL
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT B.EMP_NO, B.EMP_NAME, C.EVAL AS GRADE, C.PERCENT * B.SAL AS BONUS
FROM HR_DEPARTMENT A
JOIN HR_EMPLOYEES B ON A.DEPT_ID = B.DEPT_ID
JOIN HR_BONUS C ON B.EMP_NO = C.EMP_NO
ORDER BY EMP_NO
