
WITH REVIEW_CNT AS (
    SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE, COUNT(*) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),

MAX_REVIEW AS (
    SELECT MEMBER_ID
    FROM REVIEW_CNT
    WHERE CNT = (SELECT MAX(CNT) FROM REVIEW_CNT)
)

SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE A
JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
JOIN MAX_REVIEW C ON B.MEMBER_ID = C.MEMBER_ID
ORDER BY REVIEW_DATE, B.REVIEW_TEXT