-- 코드를 작성해주세요
-- 2022년도 한해 평가 점수가 가장 높은 사원
-- 평가점수 

WITH D AS (
    SELECT A.EMP_NO, SUM(B.SCORE) AS SCORE, A.EMP_NAME, A.POSITION, A.EMAIL, A.DEPT_ID
    FROM HR_EMPLOYEES A
    JOIN HR_GRADE B ON A.EMP_NO = B.EMP_NO
    WHERE B.YEAR = 2022
    GROUP BY B.EMP_NO
    )

SELECT MAX(D.SCORE) AS SCORE, D.EMP_NO, D.EMP_NAME, D.POSITION, D.EMAIL
FROM HR_DEPARTMENT C
JOIN D ON C.DEPT_ID = D.DEPT_ID
GROUP BY D.EMP_NO
ORDER BY SCORE DESC
LIMIT 1
