-- 코드를 입력하세요
-- 식품분류별로 가격이 제일 비싼 식품의 분류, 가격, 이름을 조회
-- 식품분류가 '과자', '국', '김치', '식용유'
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY = '과자'
    OR CATEGORY = '국'
    OR CATEGORY = '김치'
    OR CATEGORY = '식용유'
    )
ORDER BY MAX_PRICE DESC;

# SELECT * FROM FOOD_PRODUCT;