-- 코드를 입력하세요
-- 만원 단위의 가격대 별로 상품 개수를 출력
-- 0: 0 < 10000

# WITH GG AS (
    
    # SELECT
    # CASE WHEN PRICE < 10000 THEN '0'
    # ELSE IF PRICE < 20000 THEN '10000'
    # ELSE IF PRICE < 30000 THEN '20000'
    # ELSE IF PRICE < 40000 THEN '40000'
    # END AS PRICE_GROUP,
    # COUNT(PRODUCT_ID) AS PRODUCTS
    # FROM PRODUCT
    # GROUP BY PRICE_GROUP
    # ORDER BY PRICE_GROUP;
# )

# SELECT
#     CASE WHEN PRICE < 10000 THEN '0'
#     WHEN PRICE < 20000 THEN '10000'
#     WHEN PRICE < 30000 THEN '20000'
#     ELSE '40000'
#     END AS PRICE_GROUP,
#     COUNT(PRODUCT_ID) AS PRODUCTS
#     FROM PRODUCT
#     GROUP BY PRICE_GROUP
#     ORDER BY PRICE_GROUP;

# SELECT * FROM PRODUCT;


# SELECT ROUND(PRICE / 10000) * 10000 AS PRICE_GROUP, COUNT(*) AS PRODUCTS
# FROM PRODUCT
# GROUP BY ROUND(PRICE / 10000) * 10000
# ORDER BY PRICE_GROUP;

# SELECT PRICE_GROUP, COUNT(*) AS PRODUCTS
# FROM (
#   SELECT ROUND(PRICE / 10000) * 10000 AS PRICE_GROUP
#   FROM PRODUCT
# ) AS sub
# GROUP BY PRICE_GROUP
# ORDER BY PRICE_GROUP;

SELECT FLOOR(PRICE / 10000) * 10000 AS PRICE_GROUP,
       COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP;